import type { Product, Category, Order } from '@/lib/types';

export const mockCategories: Category[] = [
  { id: 'candles', name: 'Artisanal Candles', slug: 'artisanal-candles', description: 'Hand-poured artisanal candles with unique scents.' },
  { id: 'wax-figures', name: 'Wax Figures', slug: 'wax-figures', description: 'Intricately crafted wax figures for decoration.' },
  { id: 'gypsum-products', name: 'Gypsum Products', slug: 'gypsum-products', description: 'Elegant gypsum decor items.' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Lavender Bliss Candle',
    description: 'Soothing lavender scented candle, perfect for relaxation. Made with natural soy wax.',
    price: 22.99,
    category: 'Artisanal Candles',
    images: ['https://placehold.co/600x400.png?text=Lavender+Candle+1', 'https://placehold.co/600x400.png?text=Lavender+Candle+2', 'https://placehold.co/600x400.png?text=Lavender+Candle+3'],
    scent: 'Lavender',
    material: 'Soy Wax',
    dimensions: '8cm x 10cm',
    stock: 15,
    attributes: [{key: 'Color', value: 'Purple'}],
  },
  {
    id: '2',
    name: 'Vanilla Dream Candle',
    description: 'A warm and inviting vanilla bean fragrance that fills your home with comfort.',
    price: 24.50,
    category: 'Artisanal Candles',
    images: ['https://placehold.co/600x400.png?text=Vanilla+Candle+1', 'https://placehold.co/600x400.png?text=Vanilla+Candle+2'],
    scent: 'Vanilla Bean',
    material: 'Beeswax Blend',
    dimensions: '9cm x 12cm',
    stock: 20,
    attributes: [{key: 'Color', value: 'Cream'}],
  },
  {
    id: '3',
    name: 'Elegant Swan Wax Figure',
    description: 'A beautifully detailed wax figure of a swan, perfect as a centerpiece.',
    price: 35.00,
    category: 'Wax Figures',
    images: ['https://placehold.co/600x400.png?text=Swan+Wax+Figure'],
    material: 'Paraffin Wax',
    dimensions: '15cm x 12cm x 10cm',
    stock: 8,
     attributes: [{key: 'Color', value: 'White'}],
  },
  {
    id: '4',
    name: 'Geometric Gypsum Planter',
    description: 'Modern gypsum planter with a minimalist geometric design. Ideal for succulents.',
    price: 18.75,
    category: 'Gypsum Products',
    images: ['https://placehold.co/600x400.png?text=Gypsum+Planter'],
    material: 'Natural Gypsum',
    dimensions: '10cm x 10cm x 8cm',
    stock: 25,
    attributes: [{key: 'Finish', value: 'Matte White'}],
  },
  {
    id: '5',
    name: 'Rose Garden Candle',
    description: 'Experience the fragrance of a blooming rose garden with this exquisite candle.',
    price: 26.00,
    category: 'Artisanal Candles',
    images: ['https://placehold.co/600x400.png?text=Rose+Candle'],
    scent: 'Fresh Roses',
    material: 'Soy Wax',
    dimensions: '8.5cm x 11cm',
    stock: 12,
    attributes: [{key: 'Color', value: 'Pink'}],
  },
  {
    id: '6',
    name: 'Abstract Gypsum Coasters (Set of 4)',
    description: 'Protect your surfaces with style using these unique abstract design gypsum coasters.',
    price: 29.99,
    category: 'Gypsum Products',
    images: ['https://placehold.co/600x400.png?text=Gypsum+Coasters'],
    material: 'Reinforced Gypsum',
    dimensions: '10cm diameter, 1cm thick (each)',
    stock: 18,
    attributes: [{key: 'Pattern', value: 'Abstract Swirl'}],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order123',
    orderNumber: 'SCSS-001',
    date: '2023-10-26',
    status: 'Delivered',
    totalAmount: 47.49,
    items: [
      { ...mockProducts[0], quantity: 1, price: mockProducts[0].price },
      { ...mockProducts[3], quantity: 1, price: mockProducts[3].price },
    ],
  },
  {
    id: 'order124',
    orderNumber: 'SCSS-002',
    date: '2023-11-05',
    status: 'Shipped',
    totalAmount: 24.50,
    items: [{ ...mockProducts[1], quantity: 1, price: mockProducts[1].price }],
  },
  {
    id: 'order125',
    orderNumber: 'SCSS-003',
    date: '2023-11-10',
    status: 'Processing',
    totalAmount: 64.99,
    items: [
      { ...mockProducts[2], quantity: 1, price: mockProducts[2].price },
      { ...mockProducts[5], quantity: 1, price: mockProducts[5].price },
    ],
  },
];
