
import type { Product, Category, Order, MockAdminClient } from '@/lib/types';

export const mockCategories: Category[] = [
  { id: 'corporate-sets', name: 'Корпоративные наборы', slug: 'corporate-sets', description: 'Эксклюзивные наборы для корпоративных клиентов.' },
  { id: 'wedding-favors', name: 'Свадебные комплименты', slug: 'wedding-favors', description: 'Изящные комплименты для гостей на свадьбу.' },
  { id: 'scented-candles', name: 'Аромасвечи', slug: 'scented-candles', description: 'Ароматические свечи ручной работы с уникальными запахами.' },
  { id: 'tasty-home', name: 'Вкусный дом', slug: 'tasty-home', description: 'Товары для создания уюта и приятной атмосферы в доме.' }, // Slug 'tasty-home' for RU/UZ, 'home-fragrances' for EN
  { id: 'gypsum-paradise', name: 'Гипсовый рай', slug: 'gypsum-paradise', description: 'Элегантные изделия из гипса для декора.' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    sku: 'ASKM-LAV-001',
    name: 'Lavender Bliss Candle',
    description: 'Soothing lavender scented candle, perfect for relaxation. Made with natural soy wax.',
    price: 229900,
    category: 'Аромасвечи', // Changed category
    images: ['https://placehold.co/600x400.png?text=Lavender+Candle+1', 'https://placehold.co/600x400.png?text=Lavender+Candle+2', 'https://placehold.co/600x400.png?text=Lavender+Candle+3'],
    mainImage: 'https://placehold.co/600x400.png?text=Lavender+Candle+1',
    scent: 'Лаванда',
    material: 'Соевый воск',
    dimensions: '8см x 10см',
    burningTime: 'Примерно 45 часов',
    stock: 15,
    attributes: [{key: 'Цвет', value: 'Фиолетовый'}],
    isActive: true,
  },
  {
    id: '2',
    sku: 'ASKM-VAN-002',
    name: 'Vanilla Dream Candle',
    description: 'A warm and inviting vanilla bean fragrance that fills your home with comfort.',
    price: 245000,
    category: 'Аромасвечи', // Changed category
    images: ['https://placehold.co/600x400.png?text=Vanilla+Candle+1', 'https://placehold.co/600x400.png?text=Vanilla+Candle+2'],
    mainImage: 'https://placehold.co/600x400.png?text=Vanilla+Candle+1',
    scent: 'Ваниль',
    material: 'Пчелиный воск (смесь)',
    dimensions: '9см x 12см',
    burningTime: 'Примерно 60 часов',
    stock: 20,
    attributes: [{key: 'Цвет', value: 'Кремовый'}],
    isActive: true,
  },
  {
    id: '3',
    sku: 'ASKM-SWA-003',
    name: 'Elegant Swan Wax Figure',
    description: 'A beautifully detailed wax figure of a swan, perfect as a centerpiece.',
    price: 350000,
    category: 'Гипсовый рай', // Placeholder, fits better than wax figures if it's gypsum like
    images: ['https://placehold.co/600x400.png?text=Swan+Figure'],
    mainImage: 'https://placehold.co/600x400.png?text=Swan+Figure',
    scent: 'Без запаха',
    material: 'Гипс', // Assuming it's gypsum as per new category
    dimensions: '15см x 12см x 10см',
    stock: 8,
    attributes: [{key: 'Цвет', value: 'Белый'}],
    isActive: true,
  },
  {
    id: '4',
    sku: 'ASKM-GYP-004',
    name: 'Geometric Gypsum Planter',
    description: 'Modern gypsum planter with a minimalist geometric design. Ideal for succulents.',
    price: 187500,
    category: 'Гипсовый рай',
    images: ['https://placehold.co/600x400.png?text=Gypsum+Planter'],
    mainImage: 'https://placehold.co/600x400.png?text=Gypsum+Planter',
    material: 'Натуральный гипс',
    dimensions: '10см x 10см x 8см',
    stock: 25,
    attributes: [{key: 'Отделка', value: 'Матово-белая'}],
    isActive: true,
  },
  {
    id: '5',
    sku: 'ASKM-ROS-005',
    name: 'Rose Garden Candle',
    description: 'Experience the fragrance of a blooming rose garden with this exquisite candle.',
    price: 260000,
    category: 'Аромасвечи',
    images: ['https://placehold.co/600x400.png?text=Rose+Candle'],
    mainImage: 'https://placehold.co/600x400.png?text=Rose+Candle',
    scent: 'Свежие розы',
    material: 'Соевый воск',
    dimensions: '8.5см x 11см',
    burningTime: 'Примерно 50 часов',
    stock: 12,
    attributes: [{key: 'Цвет', value: 'Розовый'}],
    isActive: false, 
  },
  {
    id: '6',
    sku: 'ASKM-COA-006',
    name: 'Abstract Gypsum Coasters (Set of 4)',
    description: 'Protect your surfaces with style using these unique abstract design gypsum coasters.',
    price: 299900,
    category: 'Гипсовый рай',
    images: ['https://placehold.co/600x400.png?text=Gypsum+Coasters'],
    mainImage: 'https://placehold.co/600x400.png?text=Gypsum+Coasters',
    material: 'Усиленный гипс',
    dimensions: 'Диаметр 10см, толщина 1см (каждая)',
    stock: 0,
    attributes: [{key: 'Узор', value: 'Абстрактный вихрь'}],
    isActive: true,
  },
  {
    id: '7',
    sku: 'ASKM-CORP-001',
    name: 'Corporate Gift Set "Prestige"',
    description: 'A premium selection of scented candles and gypsum accessories, perfect for corporate gifting.',
    price: 750000,
    category: 'Корпоративные наборы',
    images: ['https://placehold.co/600x400.png?text=Corporate+Set+Prestige'],
    mainImage: 'https://placehold.co/600x400.png?text=Corporate+Set+Prestige',
    scent: 'Assorted Premium Scents',
    material: 'Soy Wax, Gypsum',
    dimensions: 'Varies per item',
    stock: 50,
    attributes: [{key: 'Packaging', value: 'Premium Gift Box'}],
    isActive: true,
  },
  {
    id: '8',
    sku: 'ASKM-WED-001',
    name: 'Wedding Favor Scented Sachet',
    description: 'Elegant scented sachets, a lovely token of appreciation for your wedding guests.',
    price: 45000, // Price per piece
    category: 'Свадебные комплименты',
    images: ['https://placehold.co/600x400.png?text=Wedding+Sachet'],
    mainImage: 'https://placehold.co/600x400.png?text=Wedding+Sachet',
    scent: 'Jasmine & Lily',
    material: 'Fabric, Scented Beads',
    dimensions: '8cm x 12cm',
    stock: 200,
    attributes: [{key: 'Custom Tag', value: 'Available upon request'}],
    isActive: true,
  },
   {
    id: '9',
    sku: 'ASKM-HOME-001',
    name: 'Home Fragrance Diffuser "Citrus Grove"',
    description: 'Brighten your home with the uplifting scent of citrus fruits.',
    price: 320000,
    category: 'Вкусный дом',
    images: ['https://placehold.co/600x400.png?text=Citrus+Diffuser'],
    mainImage: 'https://placehold.co/600x400.png?text=Citrus+Diffuser',
    scent: 'Citrus Blend',
    material: 'Glass, Reed Sticks',
    dimensions: '200ml Bottle',
    stock: 30,
    attributes: [{key: 'Duration', value: 'Approx. 3 months'}],
    isActive: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order123',
    orderNumber: 'ASKM-001',
    date: '2023-10-26',
    status: 'Delivered',
    totalAmount: mockProducts.find(p=>p.id==='1')!.price + mockProducts.find(p=>p.id==='4')!.price,
    items: [
      { ...mockProducts.find(p=>p.id==='1')!, quantity: 1, price: mockProducts.find(p=>p.id==='1')!.price },
      { ...mockProducts.find(p=>p.id==='4')!, quantity: 1, price: mockProducts.find(p=>p.id==='4')!.price },
    ],
  },
  {
    id: 'order124',
    orderNumber: 'ASKM-002',
    date: '2023-11-05',
    status: 'Shipped',
    totalAmount: mockProducts.find(p=>p.id==='2')!.price,
    items: [{ ...mockProducts.find(p=>p.id==='2')!, quantity: 1, price: mockProducts.find(p=>p.id==='2')!.price }],
  },
  {
    id: 'order125',
    orderNumber: 'ASKM-003',
    date: '2023-11-10',
    status: 'Processing',
    totalAmount: mockProducts.find(p=>p.id==='3')!.price + (mockProducts.find(p=>p.id==='5')?.price || 0), // Handled if product 5 is missing
    items: [
      { ...mockProducts.find(p=>p.id==='3')!, quantity: 1, price: mockProducts.find(p=>p.id==='3')!.price },
      ...(mockProducts.find(p=>p.id==='5') ? [{ ...mockProducts.find(p=>p.id==='5')!, quantity: 1, price: mockProducts.find(p=>p.id==='5')!.price }] : [])
    ],
  },
];

export const mockAdminClients: MockAdminClient[] = [
  { id: 'client-001', name: 'Alisher Usmanov', email: 'alisher.u@example.com', registrationDate: '2023-01-15T10:00:00Z', totalOrders: 5, totalSpent: 12500000, isBlocked: false },
  { id: 'client-002', name: 'Gulnara Karimova', email: 'gulnara.k@example.com', registrationDate: '2023-03-22T14:30:00Z', totalOrders: 2, totalSpent: 4500000, isBlocked: false },
  { id: 'client-003', name: 'Timur Begaliev', email: 'timur.b@example.com', registrationDate: '2023-05-10T09:15:00Z', totalOrders: 8, totalSpent: 21000000, isBlocked: true },
  { id: 'client-004', name: 'Dildora Ahmedova', email: 'dildora.a@example.com', registrationDate: '2023-07-01T11:00:00Z', totalOrders: 1, totalSpent: 2299000, isBlocked: false },
  { id: 'client-005', name: 'Rustam Qosimov', email: 'rustam.q@example.com', registrationDate: '2023-08-19T18:45:00Z', totalOrders: 12, totalSpent: 35000000, isBlocked: false },
];

    